-- liquibase formatted sql

-- changeset mkorolkov:1
CREATE TABLE ad_entities (
    pk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL,
    price INTEGER NOT NULL,
    image VARCHAR(100) NOT NULL,
    author INT NOT NULL,
    FOREIGN KEY (author) REFERENCES user_entities(id)
);