-- liquibase formatted sql

-- changeset mkorolkov:1
CREATE TABLE comment_entities (
    pk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at BIGINT NOT NULL,
    text VARCHAR(255) NOT NULL,
    author INT NOT NULL,
    FOREIGN KEY (author) REFERENCES user_entities(id)
);