-- liquibase formatted sql

-- changeset mkorolkov:1
CREATE TABLE comment_entities (
    pk INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    created_at BIGINT NOT NULL,
    author INT NOT NULL,
    ad_entity INT NOT NULL,
    FOREIGN KEY (author) REFERENCES user_entities(id),
    FOREIGN KEY (ad_entity) REFERENCES ad_entities(pk)
);