-- liquibase formatted sql

-- changeset mkorolkov:1
CREATE TABLE user_entities (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    authority VARCHAR(100) NOT NULL,
    image VARCHAR(100)
);